name: Check Steps
description: "checks step outcomes, prints statuses, and fails if any step did not succeed"

branding:
  color: 'green'
  icon: 'bar-chart-2'

inputs:
  steps:
    description: 'newline-separated, pipe-delimited list of "name|outcome" pairs'
    required: true

outputs:
  failed:
    description: 'whether any steps failed'
    value: ${{ steps.check.outputs.failed }}

runs:
  using: composite
  steps:
    - name: check steps
      id: check-steps
      shell: bash
      env:
        INPUT_STEPS: ${{ inputs.steps }}
      run: |
        bash ${{ github.action_path }}/lib/main.sh
