all_failed=(
  "💀 Wow. A clean sweep of failure. Impressive in its own way. 💀"
  "🎰 Jackpot! You managed to fail every single check. That takes skill. 🎰"
  "🧨 Total annihilation. Not a single check survived. 🧨"
  "🚩 Red flags everywhere. You've set a new standard for broken code. 🚩"
  "⚰️ Press F to pay respects. All checks have perished. ⚰️"
  "🌪️ Chaos incarnate. Nothing made it out alive. 🌪️"
  "💣 Mission failed successfully. Every. Single. One. 💣"
  "🏴‍☠️ Total shipwreck. Zero survivors detected. 🏴‍☠️"
  "🎪 Ladies and gentlemen, witness the rare full-spectrum failure! 🎪"
  "🔻 New record! 100% failure rate achieved. Stunning. 🔻"
  "☠️ Complete obliteration. A masterclass in breaking everything. ☠️"
  "🎯 Perfect aim! Hit every single failure condition. 🎯"
  "🌑 Total eclipse of success. Darkness prevails. 🌑"
  "💥 Scorched earth policy: nothing left standing. 💥"
  "🗿 Monumental failure. They'll write legends about this. 🗿"
  "⛔ Denied across the board. The system has spoken. ⛔"
  "🧱 Built a wall of failures. And it's spectacular. 🧱"
  "🎬 And the award for Complete Catastrophe goes to... 🎬"
  "🌋 Eruption of errors. The fallout is everywhere. 🌋"
  "🔥 Burned it all down. Every last check. 🔥"
)

partial_failed=(
  "💥 Oh noes! Looks like somebody's PR didn't pass all the checks... Better luck next time, champ. 💥"
  "🚨 Uh oh, spaghetti-o! Someone pushed code that doesn't quite... work. 🚨"
  "🎻 Sad trombone: your code has failed the vibe check. 🎻"
  "🔥 This is fine. (It's not fine.) 🔥"
  "🚧 Caution: Some assembly required. (Your code is broken.) 🚧"
  "🎲 Mixed results. Spoiler: the failures are the problem. 🎲"
  "⚠️ Houston, we have... well, several problems actually. ⚠️"
  "🛑 Stop right there! You've got some issues to address. 🛑"
  "📉 Not great, not terrible. (It's terrible.) 📉"
  "🎭 The good, the bad, and the utterly broken. Guess which is which. 🎭"
  "🌗 Half success, half disaster. Glass half broken? 🌗"
  "⚡ Some sparks of success, but mostly just smoke and errors. ⚡"
  "🎪 Step right up! See the amazing half-working code! 🎪"
  "🍕 Like a pizza with some missing slices. And those slices are on fire. 🍕"
  "🌤️ Partly cloudy with a chance of failure. (High chance.) 🌤️"
  "🎯 Hit some targets, missed others. The ones you missed? Critical. 🎯"
  "🚦 Mixed signals detected. Red lights are still red, though. 🚦"
  "📊 Your success rate graph looks... concerning. 📊"
  "🎢 What a ride! Ups, downs, and several crashes. 🎢"
  "🧩 Missing a few pieces. (The important ones.) 🧩"
)

all_success=(
  "✨ Look at you, writing code that actually works. What a concept. ✨"
  "🎉 Congrats! You managed to not break everything. Gold star. 🎉"
  "👏 Slow clap for meeting the absolute bare minimum. 👏"
  "🏆 Achievement unlocked: Basic Competency. 🏆"
  "🌟 All green! Someone's been reading the documentation. 🌟"
  "🎊 Perfect score! Try not to let it go to your head. 🎊"
  "💯 100% pass rate. You've peaked. It's all downhill from here. 💯"
  "🥇 Gold medal in not completely screwing up. Impressive. 🥇"
  "🦄 A unicorn sighting: code that works on the first try. 🦄"
  "🍾 Pop the champagne! Everything passed. (For now.) 🍾"
  "🎓 Graduated from 'breaks everything' to 'functional dev'. Proud of you. 🎓"
  "🌈 Perfect rainbow of success. Don't get used to it. 🌈"
  "🎸 Nailed it. Every. Single. Check. Rock on. 🎸"
  "🎯 Bullseye! All targets hit. Enjoy this fleeting moment. 🎯"
  "🚀 Cleared for takeoff. All systems go. (Somehow.) 🚀"
  "💎 Flawless victory. Save this screenshot. 💎"
  "🎨 A masterpiece of passing checks. Frame it. 🎨"
  "⭐ Five stars! Would merge again. ⭐"
  "🏅 Champion of not breaking things today. Tomorrow's a new day. 🏅"
  "🎺 Fanfare! Everything worked! Alert the media! 🎺"
)
